Fix apy modules tests - Re: #516
apertium/phenny pull request #522
Opened 2019-12-20 20:40 UTC by tomasff

This pull request attempts to fix issue #516.

Two changes were made:
1. In the apy module a specific value stored in the constant `SYNTAX_ERROR` is returned if a syntax error occurred. This change was made so that several functions in this module can be tested again. (Related to changes in #504)
2. A new function `check_syntax_error` was created to test if a function returns the appropriate `SYNTAX_ERROR` code.

Althought this is not a very elegant solution it should allow us to test for any problems in this module when changes occur, while a more robust solution with maybe more specific exceptions isn't implemented.

2019-12-20 22:26 UTC, Androbin commented
Maybe we could differentiate between `LINE_ERROR`, `CMD_ERROR`, `TEXT_ERROR` and so on?
LGTM otherwise :+1:

2019-12-20 23:04 UTC, tomasff commented
@Androbin Sure, that's fine. Should I maybe create an enum or a dictionary?
The dictionary could be as follows:
```python
errors = {
    'SYNTAX_ERROR': {
        'LINE_ERROR': 1,
        'CMD_ERROR': 2,
        'TEXT_ERROR': 3
    }
}
```
Or with an enum:
```python
class SyntaxError(Enum):
    	LINE_ERROR = 1
        CMD_ERROR = 2
        TEXT_ERROR = 3
```
I could also maintain the current structure of adding constants at the top. However the dictionary seems more flexible, in my opinion. Could you please let me know which solution would be best?

2019-12-21 01:43 UTC, Androbin commented
Nice writeup! I would argue for the `enum` variant. I think this best conveys the idea of getting exactly one of a known set of return values. Actually, I think we're also missing an `OK` value or similar.

2019-12-21 01:50 UTC, Androbin commented
I do have to say, this actually looks quite suspicious:
```
text, text_error = strict_check(r'.*', input.group(1), apertium_identlang)
```
Actually, after closer inspection, I can't tell why these error names were picked originally.

2019-12-21 01:54 UTC, Androbin commented
How about `KEYWORD_ERROR` for unknown sub-commands or similar, `ENUM_ERROR` for unknown source/target language or similar, and `SYNTAX_ERROR` for something that is closer to syntax errors in the classic sense like bad delimiters and stuff?

2019-12-21 01:58 UTC, Androbin commented
For example, a `strict_check` on `pairRE = langRE + '-' + langRE` might lead to either `SYNTAX_ERROR` if there's not exactly one dash, or to `ENUM_ERROR` in case the language is unknown.

2019-12-21 11:45 UTC, tomasff commented
@Androbin is this what you meant?

2019-12-21 12:53 UTC, wei2912 reviewed
I suppose there's more work to be done to integrate the other error types into the rest of the code? :P I only see `SYNTAX_ERROR` and `WEB_RESPONSE_ERROR` being used.

2019-12-21 12:53 UTC, wei2912 commented on modules/apy.py
>  SYNTAX_ERROR = 1
What's this line still doing here? :P

2019-12-21 12:53 UTC, wei2912 commented on modules/test/test_apy.py
> +            self.assertEqual(function_return_val, error, msg='No syntax error returned for {:s}!'.format(reason))
It indicates specifically "syntax error" here, which doesn't seem that general... I can't think of a more elegant solution though. Perhaps we could just restrict the function to syntax errors, as it was previously.

2019-12-21 14:02 UTC, tomasff commented on modules/apy.py
>  SYNTAX_ERROR = 1
Forgot to remove it haha. Should be removdd now.

2019-12-21 14:09 UTC, tomasff commented on modules/test/test_apy.py
> +            self.assertEqual(function_return_val, error, msg='No syntax error returned for {:s}!'.format(reason))
@wei2912 I have just pushed a solution for this. Let me know what you think.

2019-12-21 21:46 UTC, tomasff commented
@wei2912 I can integrate the other error types, however this would envolve removing a lot of the thrown `GrumbleError`. Is that alright?

2019-12-21 23:18 UTC, tomasff commented
@wei2912 @Androbin 
Update: I tried integrating other errors types by replacing `GrumbleError`'s with the new `Status` codes.

Unfortunately this broke some of the tests and I wasn't able to fix them. 

In my opinion a good separate issue/ticket would be to think about a solid structure for error handling thats consistent across all modules, and temporarily fix the apy module's tests, so that we can verify if new changes break the module.

Please let me know if I should push my attempt to replace `GrumbleError`'s with the new `Status` codes.

2019-12-22 02:19 UTC, Androbin commented
The APY tests are green now. I agree with @tomasff
@wei2912 We should merge this now and have him submit another PR.

2019-12-22 04:08 UTC, wei2912 commented
IMO I don't think it's necessary to standardise the error reporting across all the modules. In nearly any other codebase I'd agree with the need for consistent error handling, but for a modular scripts system that Begiak has, I don't think it'd lead to much payoff. We could have each module handle exceptions as best as they can (since each module would have their own exceptions to deal with), and if they're unable to do so, the bot will attempt to catch the exception and report it unless it leads to an unrecoverable error.

As for replacing `GrumbleError` with the new `Status` codes, are you speaking of modifying other modules? That can be submitted in a separate GCI task and PR.

This is related to https://github.com/apertium/phenny/issues/509.

2019-12-22 04:14 UTC, wei2912 commented
I'll be putting this into the commit message, let me know if it summarises the details well:
1. An enum was created to deal with different types of errors within the module, so that the tests can be fixed. (Related to changes in https://github.com/apertium/phenny/pull/504.)
2. A new function `check_error` was created to test exception handling.

2019-12-22 04:15 UTC, wei2912 requested changes

2019-12-22 04:15 UTC, wei2912 commented on modules/test/test_apy.py
>          self.check_exceptions(['fra (tagger nonfunc) word'], apy.apertium_perword,
Saw that the `check_exceptions` function is still being used here. Can we replace the function completely with `check_error`?

2019-12-22 13:11 UTC, tomasff commented on modules/test/test_apy.py
>          self.check_exceptions(['fra (tagger nonfunc) word'], apy.apertium_perword,
@wei2912 I have replaced it with `check_error` 👍 
I also removed `check_exceptions` as it is no longer used.

2019-12-22 13:21 UTC, tomasff commented
@wei2912 I meant replacing the use of `GrumbleError` in `handle_error` and `check_no_data`. I tried doing this, but a lot of tests related to the `translate` function broke and I wasn't able to fix them. I will try again today. Should I create an issue for this?

I think a standerdise way of handling errors would be benefitial because as of right now, errors are all handled a bit differently in every module: we're using the `Status` codes in the `apy` module and `GrumbleError`'s in other modules.

2019-12-22 22:24 UTC, wei2912 commented
@tomasff ah, I see. Please do try to replace `GrumbleError` completely and
let us know which tests break. I'll still accept your GCI submission for
fixing the tests, but will not merge until this is done.

How would the `Status` codes generalise to other modules? If you can
propose how to shift towards a standardised way, please feel free to create
an issue for it and I'll write up a few GCI tasks for that. Thanks for the
work so far!

On Sun, 22 Dec 2019, 21:21 Tomás F., <notifications@github.com> wrote:

> @wei2912 <https://github.com/wei2912> I meant replacing the use of
> GrumbleError in handle_error and check_no_data. I tried doing this, but a
> lot of tests related to the translate function broke and I wasn't able to
> fix them. I will try again today. Should I create an issue for this?
>
> I think a standerdise way of handling errors would be benefitial because
> as of right now, errors are all handled a bit differently in every module:
> we're using the Status codes in the apy module and GrumbleError's in
> other modules.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/phenny/pull/522?email_source=notifications&email_token=AAPZPF6OEQLITTRBHSLC7XDQZ5SULA5CNFSM4J6CN6LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPPV2A#issuecomment-568261352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPZPF2LT5S35DVDJ6TOCKTQZ5SULANCNFSM4J6CN6LA>
> .
>

2019-12-22 22:30 UTC, wei2912 commented
Also, no need to create a new issue for the tests failing when you replace
`GrumbleError` with `Status` in this module. Just keep us updated here on
the issues you face.

On Mon, 23 Dec 2019, 06:24 Ng Wei En, <weien1292@gmail.com> wrote:

> @tomasff ah, I see. Please do try to replace `GrumbleError` completely and
> let us know which tests break. I'll still accept your GCI submission for
> fixing the tests, but will not merge until this is done.
>
> How would the `Status` codes generalise to other modules? If you can
> propose how to shift towards a standardised way, please feel free to create
> an issue for it and I'll write up a few GCI tasks for that. Thanks for the
> work so far!
>
> On Sun, 22 Dec 2019, 21:21 Tomás F., <notifications@github.com> wrote:
>
>> @wei2912 <https://github.com/wei2912> I meant replacing the use of
>> GrumbleError in handle_error and check_no_data. I tried doing this, but
>> a lot of tests related to the translate function broke and I wasn't able
>> to fix them. I will try again today. Should I create an issue for this?
>>
>> I think a standerdise way of handling errors would be benefitial because
>> as of right now, errors are all handled a bit differently in every module:
>> we're using the Status codes in the apy module and GrumbleError's in
>> other modules.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/apertium/phenny/pull/522?email_source=notifications&email_token=AAPZPF6OEQLITTRBHSLC7XDQZ5SULA5CNFSM4J6CN6LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPPV2A#issuecomment-568261352>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAPZPF2LT5S35DVDJ6TOCKTQZ5SULANCNFSM4J6CN6LA>
>> .
>>
>

2019-12-24 00:38 UTC, tomasff commented
Sorry for the late reply.

I will try to look into this tomorrow.

On Sun, 22 Dec 2019, 22:30 Ng Wei En, <notifications@github.com> wrote:

> Also, no need to create a new issue for the tests failing when you replace
> `GrumbleError` with `Status` in this module. Just keep us updated here on
> the issues you face.
>
> On Mon, 23 Dec 2019, 06:24 Ng Wei En, <weien1292@gmail.com> wrote:
>
> > @tomasff ah, I see. Please do try to replace `GrumbleError` completely
> and
> > let us know which tests break. I'll still accept your GCI submission for
> > fixing the tests, but will not merge until this is done.
> >
> > How would the `Status` codes generalise to other modules? If you can
> > propose how to shift towards a standardised way, please feel free to
> create
> > an issue for it and I'll write up a few GCI tasks for that. Thanks for
> the
> > work so far!
> >
> > On Sun, 22 Dec 2019, 21:21 Tomás F., <notifications@github.com> wrote:
> >
> >> @wei2912 <https://github.com/wei2912> I meant replacing the use of
> >> GrumbleError in handle_error and check_no_data. I tried doing this, but
> >> a lot of tests related to the translate function broke and I wasn't able
> >> to fix them. I will try again today. Should I create an issue for this?
> >>
> >> I think a standerdise way of handling errors would be benefitial because
> >> as of right now, errors are all handled a bit differently in every
> module:
> >> we're using the Status codes in the apy module and GrumbleError's in
> >> other modules.
> >>
> >> —
> >> You are receiving this because you were mentioned.
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/apertium/phenny/pull/522?email_source=notifications&email_token=AAPZPF6OEQLITTRBHSLC7XDQZ5SULA5CNFSM4J6CN6LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPPV2A#issuecomment-568261352
> >,
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/AAPZPF2LT5S35DVDJ6TOCKTQZ5SULANCNFSM4J6CN6LA
> >
> >> .
> >>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/phenny/pull/522?email_source=notifications&email_token=ADTBQKBBL47NIYSP6IZKBGDQZ7TARA5CNFSM4J6CN6LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHP3FII#issuecomment-568308385>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTBQKGME6OWX4XJNA5W2FTQZ7TARANCNFSM4J6CN6LA>
> .
>

2019-12-28 15:58 UTC, wei2912 commented
@tomasff have there been any updates ever since your last comment? :P

2019-12-29 21:43 UTC, tomasff commented
Hi,

Not yet. I've been busy with Christmas. Hopefully I'll have it ready for
tomorrow.
So sorry for the delay

On Sat, 28 Dec 2019 at 15:58, Ng Wei En <notifications@github.com> wrote:

> @tomasff <https://github.com/tomasff> have there been any updates ever
> since your last comment? :P
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/phenny/pull/522?email_source=notifications&email_token=ADTBQKGSRQMNH5ZTWUKBXEDQ25ZSRA5CNFSM4J6CN6LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYMRBQ#issuecomment-569428102>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTBQKC2OEWOSG2WG3LRIPTQ25ZSRANCNFSM4J6CN6LA>
> .
>

2020-02-20 06:09 UTC, wei2912 commented
@tomasff Hi, I just realised this PR hasn't been merged yet... how's the progress on this? :P

2020-02-21 15:24 UTC, tomasff commented
@wei2912 Sorry for the delay, I've been busy these past weeks. I'll try to finish it by next week.

2020-02-21 15:39 UTC, wei2912 commented
No worries, please take your time! It's not an urgent matter.

On Fri, Feb 21, 2020 at 11:24 PM Tomás F. <notifications@github.com> wrote:

> @wei2912 <https://github.com/wei2912> Sorry for the delay, I've been busy
> these past weeks. I'll try to finish it by next week.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/phenny/pull/522?email_source=notifications&email_token=AAPZPFYE3M5MDEVHLRP6DYLRD7W35A5CNFSM4J6CN6LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMTBZHI#issuecomment-589700253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPZPF7GO66TAPJOEZQ3TH3RD7W35ANCNFSM4J6CN6LA>
> .
>

2026-04-05 22:35 UTC, closed without merging